# -*- coding: utf-8 -*-
"""Copy of tested_vegetabledata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14saZJmwnNjFE0A_kasOKvwDEmjXvhGkJ
"""

test_dir=r'C:\Users\maris_q3mm6nk\Desktop\FILES\data_for_ibm\Fertilizers_Recommendation_ System_For_Disease_ Prediction\Dataset Plant Disease\Veg-dataset\V

import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras.preprocessi ung.image import ImageDataGenerator

model = tf.keras.models.load_model(r'C:\Users\maris_q3mm6nk\Desktop\FILES\data_for_ibm\Fertilizers_Recommendation_ System_For_Disease_ Prediction\Dataset

test_datagen_1=ImageDataGenerator(rescale=1)
test_generator_1=test_datagen_1.flow_from_directory(
    test_dir,
    target_size=(128,128),
    batch_size=20,
    class_mode='categorical'
)
Found 3416 images belonging to 9 classes.

import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

img=image.load_img(r"C:\Users\maris_q3mm6nk\Desktop\FILES\data_for_ibm\Fertilizers_Recommendation_ System_For_Disease_ Prediction\Dataset Plant Disease\



img=image.load_img(r"C:\Users\maris_q3mm6nk\Desktop\FILES\data_for_ibm\Fertilizers_Recommendation_ System_For_Disease_ Prediction\Dataset Plant Disease\Veg-dataset\Veg-dataset\test_set\Potato___Early_blight\b7157976-61c2-4366-87c5-e3de23aa7c10___RS_Early.B 7227.jpg",target_size=(128,128))
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
y=np.argmax(model.predict(x),axis=1)
index=['Apple___Black_rot', 'Apple___healthy', 'Corn_(maize)___healthy', 'Corn_(maize)___Northern_Leaf_Blight', 'Peach___Bacterial_spot', 'Peach___healthy']
index[y[0]]
1/1 [==============================] - 0s 172ms/step

'Peach___healthy'

model.evaluate(test_generator_1,steps=50)

50/50 [==============================] - 5s 103ms/step - loss: 2.1039 - accuracy: 0.1890
[2.103949785232544, 0.1889999955892563]